# Generated by Django 3.1.7 on 2021-04-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='candidate',
            new_name='candidate_username',
        ),
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='location',
            new_name='desired_location',
        ),
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='title',
            new_name='desired_title',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='company',
            new_name='company_username',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='cover_letter',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
