# Generated by Django 3.1.7 on 2021-04-05 05:43

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField(max_length=500)),
                ('keywords', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('position_title', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('description', ckeditor.fields.RichTextField(max_length=3000)),
                ('requirements', models.TextField(max_length=3000)),
                ('benefits', ckeditor.fields.RichTextField(max_length=3000)),
                ('others', models.BooleanField(default=False)),
                ('other', ckeditor.fields.RichTextField(blank=True, max_length=3000)),
                ('remote', models.BooleanField(default=False)),
                ('candidates', models.IntegerField(default=0)),
                ('closed', models.BooleanField(default=False)),
                ('datetime_closed', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
