# Generated by Django 3.1.7 on 2021-04-05 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('CHOOSE', 'Choose'), ('SPAM', 'Spam'), ('DANGEROUS', 'Dangerous'), ('ILLEGAL', 'Illegal')], default='CHOOSE', max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('CHOOSE', 'Choose'), ('SPAM', 'Spam'), ('DANGEROUS', 'Dangerous'), ('ILLEGAL', 'Illegal')], default='CHOOSE', max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
